"use client";

/** §3.1 /review/[answerId]: question, answer, cited chunks, decision form. */

import Link from "next/link";
import { useParams, useRouter } from "next/navigation";

import { CitationCard } from "@/components/chat/CitationCard";
import { EmptyState } from "@/components/EmptyState";
import { RoleGuard } from "@/components/RoleGuard";
import { SkeletonLoader } from "@/components/SkeletonLoader";
import { ReviewDecisionForm } from "@/components/review/ReviewDecisionForm";
import { friendlyMessage } from "@/lib/errorMessages";
import type { AnswerStatus } from "@/lib/api/review";
import { useReviewDetail, useSubmitDecision } from "@/hooks/useReview";
import { useToast } from "@/providers/ToastProvider";

function ReviewDetail() {
  const { answerId } = useParams<{ answerId: string }>();
  const router = useRouter();
  const { toast } = useToast();
  const { data, isPending, isError, error } = useReviewDetail(answerId);
  const submit = useSubmitDecision(answerId);

  if (isPending) return <SkeletonLoader lines={6} />;
  if (isError) {
    return (
      <EmptyState
        title="Couldn't load this answer"
        detail={friendlyMessage(error)}
        action={
          <Link className="button" href="/review">
            Back to queue
          </Link>
        }
      />
    );
  }

  function handleDecision(decision: AnswerStatus, comment: string | null) {
    submit.mutate(
      { decision, comment },
      {
        onSuccess: (result) => {
          toast(`Answer ${result.reviewStatus}.`, "success");
          router.push("/review");
        },
        onError: (err) => toast(friendlyMessage(err)),
      },
    );
  }

  return (
    <div>
      <p>
        <Link href="/review" className="muted">
          ← Review queue
        </Link>
      </p>
      <div className="page-header">
        <h1>Review answer</h1>
        <span className={`badge answer-badge-${data.reviewStatus}`}>
          {data.reviewStatus.replace("_", " ")}
        </span>
      </div>

      <section className="review-section">
        <h2>Question</h2>
        <p className="muted">
          asked by {data.askerEmail}
        </p>
        <div className="bubble bubble-question review-question">{data.questionText}</div>
      </section>

      <section className="review-section">
        <h2>Answer</h2>
        <p className="muted">generated by {data.modelName}</p>
        <div className="bubble bubble-answer review-answer">
          <p className="answer-content">{data.content}</p>
        </div>
      </section>

      <section className="review-section">
        <h2>Cited sources</h2>
        {data.citations.length === 0 ? (
          <p className="muted">This answer cites no sources.</p>
        ) : (
          data.citations.map((citation) => (
            <CitationCard key={citation.marker} citation={citation} />
          ))
        )}
      </section>

      <ReviewDecisionForm
        allowedDecisions={data.allowedDecisions.filter((d) => d !== "pending_review")}
        pending={submit.isPending}
        onSubmit={handleDecision}
      />
    </div>
  );
}

export default function ReviewDetailPage() {
  return (
    <RoleGuard minRole="reviewer">
      <ReviewDetail />
    </RoleGuard>
  );
}
